micronaut:
  application:
    name: iot-riff
  mcp:
    server:
      transport: HTTP
      info:
        name: 'iot-riff-resources'
        version: '1.0.0'
endpoints:
  all:
    enabled: true
    sensitive: false
mongodb:
  uri: mongodb://localhost:27017/iot-riff
  database: iot-riff
mqtt:
  host: localhost
  port: 1883
  secretPath: secretPath
logger:
  levels:
    io.micronaut.http.server: DEBUG
    io.micronaut.mcp: DEBUG
kafka:
  bootstrap:
    servers: localhost:9092
  consumers:
    iot-data-processor:
      threads: 1
      auto:
        offset:
          reset: latest
vault:
  url: "http://localhost:8200"